/* Generated by Yosys 0.36 (git sha1 8f07a0d84, gcc 9.4.0-1ubuntu1~20.04.2 -fPIC -Os) */

(* dynports =  1  *)
(* hdlname = "\\MSKg16mul_hpc3" *)
(* src = "gadget_library/MSK/MSKg16mul_hpc3.v:18.1-120.10" *)
module \$paramod\MSKg16mul_hpc3\d=s32'00000000000000000000000000000010 (ina0, ina1, ina2, ina3, inb0, inb1, inb2, inb3, ina0_prev, ina1_prev, ina2_prev, ina3_prev, rnd, clk, out0, out1, out2, out3);
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:82.35-82.42" *)
  wire [3:0] \ParProdI[0].ParProdJ[1].NotEq.mul1_in ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:82.44-82.52" *)
  wire [3:0] \ParProdI[0].ParProdJ[1].NotEq.mul1_out ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:82.24-82.33" *)
  wire [3:0] \ParProdI[0].ParProdJ[1].NotEq.u_j2_comb ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:103.24-103.28" *)
  wire [3:0] \ParProdI[0].ParProdJ[1].NotEq.v_j2 ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:102.24-102.33" *)
  wire [3:0] \ParProdI[0].ParProdJ[1].NotEq.v_j2_comb ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:74.18-74.20" *)
  wire \ParProdI[0].u0 ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:74.22-74.24" *)
  wire \ParProdI[0].u1 ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:74.26-74.28" *)
  wire \ParProdI[0].u2 ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:74.30-74.32" *)
  wire \ParProdI[0].u3 ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:74.34-74.36" *)
  wire \ParProdI[0].v0 ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:74.38-74.40" *)
  wire \ParProdI[0].v1 ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:74.42-74.44" *)
  wire \ParProdI[0].v2 ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:74.46-74.48" *)
  wire \ParProdI[0].v3 ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:82.35-82.42" *)
  wire [3:0] \ParProdI[1].ParProdJ[0].NotEq.mul1_in ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:82.44-82.52" *)
  wire [3:0] \ParProdI[1].ParProdJ[0].NotEq.mul1_out ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:82.24-82.33" *)
  wire [3:0] \ParProdI[1].ParProdJ[0].NotEq.u_j2_comb ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:103.24-103.28" *)
  wire [3:0] \ParProdI[1].ParProdJ[0].NotEq.v_j2 ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:102.24-102.33" *)
  wire [3:0] \ParProdI[1].ParProdJ[0].NotEq.v_j2_comb ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:74.18-74.20" *)
  wire \ParProdI[1].u0 ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:74.22-74.24" *)
  wire \ParProdI[1].u1 ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:74.26-74.28" *)
  wire \ParProdI[1].u2 ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:74.30-74.32" *)
  wire \ParProdI[1].u3 ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:74.34-74.36" *)
  wire \ParProdI[1].v0 ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:74.38-74.40" *)
  wire \ParProdI[1].v1 ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:74.42-74.44" *)
  wire \ParProdI[1].v2 ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:74.46-74.48" *)
  wire \ParProdI[1].v3 ;
  (* fv_type = "clock" *)
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:44.31-44.34" *)
  input clk;
  wire clk;
  (* fv_latency = 32'd0 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:41.58-41.62" *)
  input [1:0] ina0;
  wire [1:0] ina0;
  (* fv_latency = 32'd1 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:42.58-42.67" *)
  input [1:0] ina0_prev;
  wire [1:0] ina0_prev;
  (* fv_latency = 32'd0 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:41.64-41.68" *)
  input [1:0] ina1;
  wire [1:0] ina1;
  (* fv_latency = 32'd1 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:42.69-42.78" *)
  input [1:0] ina1_prev;
  wire [1:0] ina1_prev;
  (* fv_latency = 32'd0 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:41.70-41.74" *)
  input [1:0] ina2;
  wire [1:0] ina2;
  (* fv_latency = 32'd1 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:42.80-42.89" *)
  input [1:0] ina2_prev;
  wire [1:0] ina2_prev;
  (* fv_latency = 32'd0 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:41.76-41.80" *)
  input [1:0] ina3;
  wire [1:0] ina3;
  (* fv_latency = 32'd1 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:42.91-42.100" *)
  input [1:0] ina3_prev;
  wire [1:0] ina3_prev;
  (* fv_latency = 32'd0 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:43.58-43.62" *)
  input [1:0] inb0;
  wire [1:0] inb0;
  (* fv_latency = 32'd0 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:43.64-43.68" *)
  input [1:0] inb1;
  wire [1:0] inb1;
  (* fv_latency = 32'd0 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:43.70-43.74" *)
  input [1:0] inb2;
  wire [1:0] inb2;
  (* fv_latency = 32'd0 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:43.76-43.80" *)
  input [1:0] inb3;
  wire [1:0] inb3;
  (* fv_latency = 32'd1 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:45.58-45.62" *)
  output [1:0] out0;
  wire [1:0] out0;
  (* fv_latency = 32'd1 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:45.64-45.68" *)
  output [1:0] out1;
  wire [1:0] out1;
  (* fv_latency = 32'd1 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:45.70-45.74" *)
  output [1:0] out2;
  wire [1:0] out2;
  (* fv_latency = 32'd1 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:45.76-45.80" *)
  output [1:0] out3;
  wire [1:0] out3;
  (* fv_count = 32'd1 *)
  (* fv_rnd_count_0 = 32'd8 *)
  (* fv_rnd_lat_0 = 32'd0 *)
  (* fv_type = "random" *)
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:47.23-47.26" *)
  input [7:0] rnd;
  wire [7:0] rnd;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:54.22-54.26" *)
  wire [3:0] rnd0;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:55.22-55.26" *)
  wire [3:0] rnd1;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:56.12-56.20" *)
  wire [3:0] \rnd_mat0[0] ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:56.12-56.20" *)
  wire [3:0] \rnd_mat0[1] ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:56.12-56.20" *)
  wire [3:0] \rnd_mat0[2] ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:56.12-56.20" *)
  wire [3:0] \rnd_mat0[3] ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:57.12-57.20" *)
  wire [3:0] \rnd_mat1[0] ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:57.12-57.20" *)
  wire [3:0] \rnd_mat1[1] ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:57.12-57.20" *)
  wire [3:0] \rnd_mat1[2] ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:57.12-57.20" *)
  wire [3:0] \rnd_mat1[3] ;
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:62.17-62.23" *)
  wire [31:0] \rnd_mat_i[0].rnd_mat_j[1].offset ;
  XOR2_X1 _00_ (
    .A(\ParProdI[0].u0 ),
    .B(\ParProdI[0].v0 ),
    .Z(out0[0])
  );
  XOR2_X1 _01_ (
    .A(\ParProdI[0].u1 ),
    .B(\ParProdI[0].v1 ),
    .Z(out1[0])
  );
  XOR2_X1 _02_ (
    .A(\ParProdI[0].u2 ),
    .B(\ParProdI[0].v2 ),
    .Z(out2[0])
  );
  XOR2_X1 _03_ (
    .A(\ParProdI[0].u3 ),
    .B(\ParProdI[0].v3 ),
    .Z(out3[0])
  );
  XOR2_X1 _04_ (
    .A(\ParProdI[0].ParProdJ[1].NotEq.mul1_out [0]),
    .B(rnd[4]),
    .Z(\ParProdI[0].ParProdJ[1].NotEq.u_j2_comb [0])
  );
  XOR2_X1 _05_ (
    .A(\ParProdI[0].ParProdJ[1].NotEq.mul1_out [1]),
    .B(rnd[5]),
    .Z(\ParProdI[0].ParProdJ[1].NotEq.u_j2_comb [1])
  );
  XOR2_X1 _06_ (
    .A(\ParProdI[0].ParProdJ[1].NotEq.mul1_out [2]),
    .B(rnd[6]),
    .Z(\ParProdI[0].ParProdJ[1].NotEq.u_j2_comb [2])
  );
  XOR2_X1 _07_ (
    .A(\ParProdI[0].ParProdJ[1].NotEq.mul1_out [3]),
    .B(rnd[7]),
    .Z(\ParProdI[0].ParProdJ[1].NotEq.u_j2_comb [3])
  );
  XOR2_X1 _08_ (
    .A(inb0[1]),
    .B(rnd[0]),
    .Z(\ParProdI[0].ParProdJ[1].NotEq.v_j2_comb [0])
  );
  XOR2_X1 _09_ (
    .A(inb1[1]),
    .B(rnd[1]),
    .Z(\ParProdI[0].ParProdJ[1].NotEq.v_j2_comb [1])
  );
  XOR2_X1 _10_ (
    .A(inb2[1]),
    .B(rnd[2]),
    .Z(\ParProdI[0].ParProdJ[1].NotEq.v_j2_comb [2])
  );
  XOR2_X1 _11_ (
    .A(inb3[1]),
    .B(rnd[3]),
    .Z(\ParProdI[0].ParProdJ[1].NotEq.v_j2_comb [3])
  );
  XOR2_X1 _12_ (
    .A(\ParProdI[1].u0 ),
    .B(\ParProdI[1].v0 ),
    .Z(out0[1])
  );
  XOR2_X1 _13_ (
    .A(\ParProdI[1].u1 ),
    .B(\ParProdI[1].v1 ),
    .Z(out1[1])
  );
  XOR2_X1 _14_ (
    .A(\ParProdI[1].u2 ),
    .B(\ParProdI[1].v2 ),
    .Z(out2[1])
  );
  XOR2_X1 _15_ (
    .A(\ParProdI[1].u3 ),
    .B(\ParProdI[1].v3 ),
    .Z(out3[1])
  );
  XOR2_X1 _16_ (
    .A(rnd[4]),
    .B(\ParProdI[1].ParProdJ[0].NotEq.mul1_out [0]),
    .Z(\ParProdI[1].ParProdJ[0].NotEq.u_j2_comb [0])
  );
  XOR2_X1 _17_ (
    .A(rnd[5]),
    .B(\ParProdI[1].ParProdJ[0].NotEq.mul1_out [1]),
    .Z(\ParProdI[1].ParProdJ[0].NotEq.u_j2_comb [1])
  );
  XOR2_X1 _18_ (
    .A(rnd[6]),
    .B(\ParProdI[1].ParProdJ[0].NotEq.mul1_out [2]),
    .Z(\ParProdI[1].ParProdJ[0].NotEq.u_j2_comb [2])
  );
  XOR2_X1 _19_ (
    .A(rnd[7]),
    .B(\ParProdI[1].ParProdJ[0].NotEq.mul1_out [3]),
    .Z(\ParProdI[1].ParProdJ[0].NotEq.u_j2_comb [3])
  );
  XOR2_X1 _20_ (
    .A(rnd[0]),
    .B(inb0[0]),
    .Z(\ParProdI[0].ParProdJ[1].NotEq.mul1_in [0])
  );
  XOR2_X1 _21_ (
    .A(rnd[1]),
    .B(inb1[0]),
    .Z(\ParProdI[0].ParProdJ[1].NotEq.mul1_in [1])
  );
  XOR2_X1 _22_ (
    .A(rnd[2]),
    .B(inb2[0]),
    .Z(\ParProdI[0].ParProdJ[1].NotEq.mul1_in [2])
  );
  XOR2_X1 _23_ (
    .A(rnd[3]),
    .B(inb3[0]),
    .Z(\ParProdI[0].ParProdJ[1].NotEq.mul1_in [3])
  );
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:96.30-100.14" *)
  \$paramod\bin_REG\W=s32'00000000000000000000000000000100  \ParProdI[0].ParProdJ[1].NotEq.REGin_u  (
    .clk(clk),
    .in(\ParProdI[0].ParProdJ[1].NotEq.u_j2_comb ),
    .out({ \ParProdI[0].u3 , \ParProdI[0].u2 , \ParProdI[0].u1 , \ParProdI[0].u0  })
  );
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:104.30-108.14" *)
  \$paramod\bin_REG\W=s32'00000000000000000000000000000100  \ParProdI[0].ParProdJ[1].NotEq.REGin_v2  (
    .clk(clk),
    .in(\ParProdI[0].ParProdJ[1].NotEq.v_j2_comb ),
    .out(\ParProdI[0].ParProdJ[1].NotEq.v_j2 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:90.21-94.14" *)
  G16_mul \ParProdI[0].ParProdJ[1].NotEq.g16mul_inst1  (
    .x({ ina3[0], ina2[0], ina1[0], ina0[0] }),
    .y(\ParProdI[0].ParProdJ[1].NotEq.mul1_in ),
    .z(\ParProdI[0].ParProdJ[1].NotEq.mul1_out )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:109.21-113.14" *)
  G16_mul \ParProdI[0].ParProdJ[1].NotEq.g16mul_inst2  (
    .x({ ina3_prev[0], ina2_prev[0], ina1_prev[0], ina0_prev[0] }),
    .y(\ParProdI[0].ParProdJ[1].NotEq.v_j2 ),
    .z({ \ParProdI[0].v3 , \ParProdI[0].v2 , \ParProdI[0].v1 , \ParProdI[0].v0  })
  );
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:96.30-100.14" *)
  \$paramod\bin_REG\W=s32'00000000000000000000000000000100  \ParProdI[1].ParProdJ[0].NotEq.REGin_u  (
    .clk(clk),
    .in(\ParProdI[1].ParProdJ[0].NotEq.u_j2_comb ),
    .out({ \ParProdI[1].u3 , \ParProdI[1].u2 , \ParProdI[1].u1 , \ParProdI[1].u0  })
  );
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:104.30-108.14" *)
  \$paramod\bin_REG\W=s32'00000000000000000000000000000100  \ParProdI[1].ParProdJ[0].NotEq.REGin_v2  (
    .clk(clk),
    .in(\ParProdI[0].ParProdJ[1].NotEq.mul1_in ),
    .out(\ParProdI[1].ParProdJ[0].NotEq.v_j2 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:90.21-94.14" *)
  G16_mul \ParProdI[1].ParProdJ[0].NotEq.g16mul_inst1  (
    .x({ ina3[1], ina2[1], ina1[1], ina0[1] }),
    .y(\ParProdI[0].ParProdJ[1].NotEq.v_j2_comb ),
    .z(\ParProdI[1].ParProdJ[0].NotEq.mul1_out )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "gadget_library/MSK/MSKg16mul_hpc3.v:109.21-113.14" *)
  G16_mul \ParProdI[1].ParProdJ[0].NotEq.g16mul_inst2  (
    .x({ ina3_prev[1], ina2_prev[1], ina1_prev[1], ina0_prev[1] }),
    .y(\ParProdI[1].ParProdJ[0].NotEq.v_j2 ),
    .z({ \ParProdI[1].v3 , \ParProdI[1].v2 , \ParProdI[1].v1 , \ParProdI[1].v0  })
  );
  assign \ParProdI[1].ParProdJ[0].NotEq.mul1_in  = \ParProdI[0].ParProdJ[1].NotEq.v_j2_comb ;
  assign \ParProdI[1].ParProdJ[0].NotEq.v_j2_comb  = \ParProdI[0].ParProdJ[1].NotEq.mul1_in ;
  assign rnd0 = rnd[3:0];
  assign rnd1 = rnd[7:4];
  assign \rnd_mat0[0]  = 4'h0;
  assign \rnd_mat0[1]  = rnd[3:0];
  assign \rnd_mat0[2]  = rnd[3:0];
  assign \rnd_mat0[3]  = 4'h0;
  assign \rnd_mat1[0]  = 4'h0;
  assign \rnd_mat1[1]  = rnd[7:4];
  assign \rnd_mat1[2]  = rnd[7:4];
  assign \rnd_mat1[3]  = 4'h0;
  assign \rnd_mat_i[0].rnd_mat_j[1].offset  = 32'd0;
endmodule

(* dynports =  1  *)
(* hdlname = "\\MSKg4mul_hpc3" *)
(* src = "gadget_library/MSK/MSKg4mul_hpc3.v:18.1-99.10" *)
module \$paramod\MSKg4mul_hpc3\d=s32'00000000000000000000000000000010 (ina0, ina1, inb0, inb1, ina0_prev, ina1_prev, rnd, clk, out0, out1);
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:61.35-61.42" *)
  wire [1:0] \ParProdI[0].ParProdJ[1].NotEq.mul1_in ;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:61.44-61.52" *)
  wire [1:0] \ParProdI[0].ParProdJ[1].NotEq.mul1_out ;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:61.24-61.33" *)
  wire [1:0] \ParProdI[0].ParProdJ[1].NotEq.u_j2_comb ;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:82.24-82.28" *)
  wire [1:0] \ParProdI[0].ParProdJ[1].NotEq.v_j2 ;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:81.24-81.33" *)
  wire [1:0] \ParProdI[0].ParProdJ[1].NotEq.v_j2_comb ;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:55.18-55.20" *)
  wire \ParProdI[0].u0 ;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:55.22-55.24" *)
  wire \ParProdI[0].u1 ;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:55.26-55.28" *)
  wire \ParProdI[0].v0 ;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:55.30-55.32" *)
  wire \ParProdI[0].v1 ;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:61.35-61.42" *)
  wire [1:0] \ParProdI[1].ParProdJ[0].NotEq.mul1_in ;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:61.44-61.52" *)
  wire [1:0] \ParProdI[1].ParProdJ[0].NotEq.mul1_out ;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:61.24-61.33" *)
  wire [1:0] \ParProdI[1].ParProdJ[0].NotEq.u_j2_comb ;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:82.24-82.28" *)
  wire [1:0] \ParProdI[1].ParProdJ[0].NotEq.v_j2 ;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:81.24-81.33" *)
  wire [1:0] \ParProdI[1].ParProdJ[0].NotEq.v_j2_comb ;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:55.18-55.20" *)
  wire \ParProdI[1].u0 ;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:55.22-55.24" *)
  wire \ParProdI[1].u1 ;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:55.26-55.28" *)
  wire \ParProdI[1].v0 ;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:55.30-55.32" *)
  wire \ParProdI[1].v1 ;
  (* fv_type = "clock" *)
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:25.31-25.34" *)
  input clk;
  wire clk;
  (* fv_latency = 32'd0 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:22.58-22.62" *)
  input [1:0] ina0;
  wire [1:0] ina0;
  (* fv_latency = 32'd1 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:23.58-23.67" *)
  input [1:0] ina0_prev;
  wire [1:0] ina0_prev;
  (* fv_latency = 32'd0 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:22.64-22.68" *)
  input [1:0] ina1;
  wire [1:0] ina1;
  (* fv_latency = 32'd1 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:23.69-23.78" *)
  input [1:0] ina1_prev;
  wire [1:0] ina1_prev;
  (* fv_latency = 32'd0 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:24.58-24.62" *)
  input [1:0] inb0;
  wire [1:0] inb0;
  (* fv_latency = 32'd0 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:24.64-24.68" *)
  input [1:0] inb1;
  wire [1:0] inb1;
  (* fv_latency = 32'd1 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:26.58-26.62" *)
  output [1:0] out0;
  wire [1:0] out0;
  (* fv_latency = 32'd1 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:26.64-26.68" *)
  output [1:0] out1;
  wire [1:0] out1;
  (* fv_count = 32'd1 *)
  (* fv_rnd_count_0 = 32'd4 *)
  (* fv_rnd_lat_0 = 32'd0 *)
  (* fv_type = "random" *)
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:28.23-28.26" *)
  input [3:0] rnd;
  wire [3:0] rnd;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:35.22-35.26" *)
  wire [1:0] rnd0;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:36.22-36.26" *)
  wire [1:0] rnd1;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:37.12-37.20" *)
  wire [1:0] \rnd_mat0[0] ;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:37.12-37.20" *)
  wire [1:0] \rnd_mat0[1] ;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:37.12-37.20" *)
  wire [1:0] \rnd_mat0[2] ;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:37.12-37.20" *)
  wire [1:0] \rnd_mat0[3] ;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:38.12-38.20" *)
  wire [1:0] \rnd_mat1[0] ;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:38.12-38.20" *)
  wire [1:0] \rnd_mat1[1] ;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:38.12-38.20" *)
  wire [1:0] \rnd_mat1[2] ;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:38.12-38.20" *)
  wire [1:0] \rnd_mat1[3] ;
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:43.17-43.23" *)
  wire [31:0] \rnd_mat_i[0].rnd_mat_j[1].offset ;
  XOR2_X1 _00_ (
    .A(\ParProdI[0].u0 ),
    .B(\ParProdI[0].v0 ),
    .Z(out0[0])
  );
  XOR2_X1 _01_ (
    .A(\ParProdI[0].u1 ),
    .B(\ParProdI[0].v1 ),
    .Z(out1[0])
  );
  XOR2_X1 _02_ (
    .A(\ParProdI[0].ParProdJ[1].NotEq.mul1_out [0]),
    .B(rnd[2]),
    .Z(\ParProdI[0].ParProdJ[1].NotEq.u_j2_comb [0])
  );
  XOR2_X1 _03_ (
    .A(\ParProdI[0].ParProdJ[1].NotEq.mul1_out [1]),
    .B(rnd[3]),
    .Z(\ParProdI[0].ParProdJ[1].NotEq.u_j2_comb [1])
  );
  XOR2_X1 _04_ (
    .A(inb0[1]),
    .B(rnd[0]),
    .Z(\ParProdI[0].ParProdJ[1].NotEq.v_j2_comb [0])
  );
  XOR2_X1 _05_ (
    .A(inb1[1]),
    .B(rnd[1]),
    .Z(\ParProdI[0].ParProdJ[1].NotEq.v_j2_comb [1])
  );
  XOR2_X1 _06_ (
    .A(\ParProdI[1].u0 ),
    .B(\ParProdI[1].v0 ),
    .Z(out0[1])
  );
  XOR2_X1 _07_ (
    .A(\ParProdI[1].u1 ),
    .B(\ParProdI[1].v1 ),
    .Z(out1[1])
  );
  XOR2_X1 _08_ (
    .A(rnd[2]),
    .B(\ParProdI[1].ParProdJ[0].NotEq.mul1_out [0]),
    .Z(\ParProdI[1].ParProdJ[0].NotEq.u_j2_comb [0])
  );
  XOR2_X1 _09_ (
    .A(rnd[3]),
    .B(\ParProdI[1].ParProdJ[0].NotEq.mul1_out [1]),
    .Z(\ParProdI[1].ParProdJ[0].NotEq.u_j2_comb [1])
  );
  XOR2_X1 _10_ (
    .A(rnd[0]),
    .B(inb0[0]),
    .Z(\ParProdI[0].ParProdJ[1].NotEq.mul1_in [0])
  );
  XOR2_X1 _11_ (
    .A(rnd[1]),
    .B(inb1[0]),
    .Z(\ParProdI[0].ParProdJ[1].NotEq.mul1_in [1])
  );
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:75.30-79.14" *)
  \$paramod\bin_REG\W=s32'00000000000000000000000000000010  \ParProdI[0].ParProdJ[1].NotEq.REGin_u  (
    .clk(clk),
    .in(\ParProdI[0].ParProdJ[1].NotEq.u_j2_comb ),
    .out({ \ParProdI[0].u1 , \ParProdI[0].u0  })
  );
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:83.30-87.14" *)
  \$paramod\bin_REG\W=s32'00000000000000000000000000000010  \ParProdI[0].ParProdJ[1].NotEq.REGin_v2  (
    .clk(clk),
    .in(\ParProdI[0].ParProdJ[1].NotEq.v_j2_comb ),
    .out(\ParProdI[0].ParProdJ[1].NotEq.v_j2 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:69.20-73.14" *)
  G4_mul \ParProdI[0].ParProdJ[1].NotEq.g4mul_inst1  (
    .x({ ina1[0], ina0[0] }),
    .y(\ParProdI[0].ParProdJ[1].NotEq.mul1_in ),
    .z(\ParProdI[0].ParProdJ[1].NotEq.mul1_out )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:88.20-92.14" *)
  G4_mul \ParProdI[0].ParProdJ[1].NotEq.g4mul_inst2  (
    .x({ ina1_prev[0], ina0_prev[0] }),
    .y(\ParProdI[0].ParProdJ[1].NotEq.v_j2 ),
    .z({ \ParProdI[0].v1 , \ParProdI[0].v0  })
  );
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:75.30-79.14" *)
  \$paramod\bin_REG\W=s32'00000000000000000000000000000010  \ParProdI[1].ParProdJ[0].NotEq.REGin_u  (
    .clk(clk),
    .in(\ParProdI[1].ParProdJ[0].NotEq.u_j2_comb ),
    .out({ \ParProdI[1].u1 , \ParProdI[1].u0  })
  );
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:83.30-87.14" *)
  \$paramod\bin_REG\W=s32'00000000000000000000000000000010  \ParProdI[1].ParProdJ[0].NotEq.REGin_v2  (
    .clk(clk),
    .in(\ParProdI[0].ParProdJ[1].NotEq.mul1_in ),
    .out(\ParProdI[1].ParProdJ[0].NotEq.v_j2 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:69.20-73.14" *)
  G4_mul \ParProdI[1].ParProdJ[0].NotEq.g4mul_inst1  (
    .x({ ina1[1], ina0[1] }),
    .y(\ParProdI[0].ParProdJ[1].NotEq.v_j2_comb ),
    .z(\ParProdI[1].ParProdJ[0].NotEq.mul1_out )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "gadget_library/MSK/MSKg4mul_hpc3.v:88.20-92.14" *)
  G4_mul \ParProdI[1].ParProdJ[0].NotEq.g4mul_inst2  (
    .x({ ina1_prev[1], ina0_prev[1] }),
    .y(\ParProdI[1].ParProdJ[0].NotEq.v_j2 ),
    .z({ \ParProdI[1].v1 , \ParProdI[1].v0  })
  );
  assign \ParProdI[1].ParProdJ[0].NotEq.mul1_in  = \ParProdI[0].ParProdJ[1].NotEq.v_j2_comb ;
  assign \ParProdI[1].ParProdJ[0].NotEq.v_j2_comb  = \ParProdI[0].ParProdJ[1].NotEq.mul1_in ;
  assign rnd0 = rnd[1:0];
  assign rnd1 = rnd[3:2];
  assign \rnd_mat0[0]  = 2'h0;
  assign \rnd_mat0[1]  = rnd[1:0];
  assign \rnd_mat0[2]  = rnd[1:0];
  assign \rnd_mat0[3]  = 2'h0;
  assign \rnd_mat1[0]  = 2'h0;
  assign \rnd_mat1[1]  = rnd[3:2];
  assign \rnd_mat1[2]  = rnd[3:2];
  assign \rnd_mat1[3]  = 2'h0;
  assign \rnd_mat_i[0].rnd_mat_j[1].offset  = 32'd0;
endmodule

(* dynports =  1  *)
(* hdlname = "\\MSKinv" *)
(* src = "gadget_library/MSK/MSKinv.v:18.1-34.10" *)
module \$paramod\MSKinv\d=s32'00000000000000000000000000000010 (in, out);
  (* fv_count = 32'd1 *)
  (* fv_latency = 32'd0 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKinv.v:21.80-21.82" *)
  input [1:0] in;
  wire [1:0] in;
  (* fv_count = 32'd1 *)
  (* fv_latency = 32'd0 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKinv.v:22.80-22.83" *)
  output [1:0] out;
  wire [1:0] out;
  INV_X1 _0_ (
    .A(in[0]),
    .ZN(out[0])
  );
  assign out[1] = in[1];
endmodule

(* dynports =  1  *)
(* hdlname = "\\MSKreg" *)
(* src = "gadget_library/MSK/MSKreg.v:18.1-31.10" *)
module \$paramod\MSKreg\d=s32'00000000000000000000000000000010 (clk, in, out);
  wire _0_;
  wire _1_;
  (* fv_type = "clock" *)
  (* src = "gadget_library/MSK/MSKreg.v:20.33-20.36" *)
  input clk;
  wire clk;
  (* fv_count = 32'd1 *)
  (* fv_latency = 32'd0 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKreg.v:21.80-21.82" *)
  input [1:0] in;
  wire [1:0] in;
  (* fv_count = 32'd1 *)
  (* fv_latency = 32'd1 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKreg.v:22.80-22.83" *)
  output [1:0] out;
  wire [1:0] out;
  (* src = "gadget_library/MSK/MSKreg.v:24.19-24.24" *)
  wire [1:0] state;
  (* src = "gadget_library/MSK/MSKreg.v:26.1-27.17" *)
  DFF_X1 _2_ (
    .CK(clk),
    .D(in[0]),
    .Q(state[0]),
    .QN(_1_)
  );
  (* src = "gadget_library/MSK/MSKreg.v:26.1-27.17" *)
  DFF_X1 _3_ (
    .CK(clk),
    .D(in[1]),
    .Q(state[1]),
    .QN(_0_)
  );
  assign out = state;
endmodule

(* dynports =  1  *)
(* hdlname = "\\MSKxor" *)
(* src = "gadget_library/MSK/MSKxor.v:18.1-25.10" *)
module \$paramod\MSKxor\d=s32'00000000000000000000000000000010 (ina, inb, out);
  (* fv_count = 32'd1 *)
  (* fv_latency = 32'd0 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKxor.v:20.80-20.83" *)
  input [1:0] ina;
  wire [1:0] ina;
  (* fv_count = 32'd1 *)
  (* fv_latency = 32'd0 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKxor.v:20.85-20.88" *)
  input [1:0] inb;
  wire [1:0] inb;
  (* fv_count = 32'd1 *)
  (* fv_latency = 32'd0 *)
  (* fv_type = "sharing" *)
  (* src = "gadget_library/MSK/MSKxor.v:21.80-21.83" *)
  output [1:0] out;
  wire [1:0] out;
  XOR2_X1 _0_ (
    .A(ina[0]),
    .B(inb[0]),
    .Z(out[0])
  );
  XOR2_X1 _1_ (
    .A(ina[1]),
    .B(inb[1]),
    .Z(out[1])
  );
endmodule

(* keep_hierarchy = "yes" *)
(* hdlname = "\\bin_REG" *)
(* dynports =  1  *)
(* DONT_TOUCH = "yes" *)
(* src = "gadget_library/BIN/bin_REG.v:13.1-30.10" *)
module \$paramod\bin_REG\W=s32'00000000000000000000000000000010 (clk, in, out);
  wire _0_;
  wire _1_;
  (* src = "gadget_library/BIN/bin_REG.v:19.11-19.14" *)
  input clk;
  wire clk;
  (* src = "gadget_library/BIN/bin_REG.v:20.19-20.21" *)
  input [1:0] in;
  wire [1:0] in;
  (* src = "gadget_library/BIN/bin_REG.v:21.20-21.23" *)
  output [1:0] out;
  wire [1:0] out;
  (* src = "gadget_library/BIN/bin_REG.v:24.13-24.17" *)
  wire [1:0] regi;
  (* src = "gadget_library/BIN/bin_REG.v:25.1-26.16" *)
  DFF_X1 _2_ (
    .CK(clk),
    .D(in[0]),
    .Q(regi[0]),
    .QN(_1_)
  );
  (* src = "gadget_library/BIN/bin_REG.v:25.1-26.16" *)
  DFF_X1 _3_ (
    .CK(clk),
    .D(in[1]),
    .Q(regi[1]),
    .QN(_0_)
  );
  assign out = regi;
endmodule

(* keep_hierarchy = "yes" *)
(* hdlname = "\\bin_REG" *)
(* dynports =  1  *)
(* DONT_TOUCH = "yes" *)
(* src = "gadget_library/BIN/bin_REG.v:13.1-30.10" *)
module \$paramod\bin_REG\W=s32'00000000000000000000000000000100 (clk, in, out);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  (* src = "gadget_library/BIN/bin_REG.v:19.11-19.14" *)
  input clk;
  wire clk;
  (* src = "gadget_library/BIN/bin_REG.v:20.19-20.21" *)
  input [3:0] in;
  wire [3:0] in;
  (* src = "gadget_library/BIN/bin_REG.v:21.20-21.23" *)
  output [3:0] out;
  wire [3:0] out;
  (* src = "gadget_library/BIN/bin_REG.v:24.13-24.17" *)
  wire [3:0] regi;
  (* src = "gadget_library/BIN/bin_REG.v:25.1-26.16" *)
  DFF_X1 _4_ (
    .CK(clk),
    .D(in[0]),
    .Q(regi[0]),
    .QN(_1_)
  );
  (* src = "gadget_library/BIN/bin_REG.v:25.1-26.16" *)
  DFF_X1 _5_ (
    .CK(clk),
    .D(in[1]),
    .Q(regi[1]),
    .QN(_2_)
  );
  (* src = "gadget_library/BIN/bin_REG.v:25.1-26.16" *)
  DFF_X1 _6_ (
    .CK(clk),
    .D(in[2]),
    .Q(regi[2]),
    .QN(_3_)
  );
  (* src = "gadget_library/BIN/bin_REG.v:25.1-26.16" *)
  DFF_X1 _7_ (
    .CK(clk),
    .D(in[3]),
    .Q(regi[3]),
    .QN(_0_)
  );
  assign out = regi;
endmodule

(* src = "gadget_library/MSK/G16_mul.v:12.1-24.10" *)
module G16_mul(x, y, z);
  (* src = "gadget_library/MSK/G16_mul.v:18.20-18.25" *)
  wire _00_;
  (* src = "gadget_library/MSK/G16_mul.v:18.20-18.25" *)
  wire _01_;
  (* src = "gadget_library/MSK/G16_mul.v:18.31-18.36" *)
  wire _02_;
  (* src = "gadget_library/MSK/G16_mul.v:18.31-18.36" *)
  wire _03_;
  (* src = "gadget_library/MSK/G16_mul.v:13.16-13.17" *)
  wire [1:0] a;
  (* src = "gadget_library/MSK/G16_mul.v:13.19-13.20" *)
  wire [1:0] b;
  (* src = "gadget_library/MSK/G16_mul.v:13.22-13.23" *)
  wire [1:0] c;
  (* src = "gadget_library/MSK/G16_mul.v:13.25-13.26" *)
  wire [1:0] d;
  (* src = "gadget_library/MSK/G16_mul.v:13.28-13.29" *)
  wire [1:0] e;
  (* src = "gadget_library/MSK/G16_mul.v:13.31-13.36" *)
  wire [1:0] e_scl;
  (* src = "gadget_library/MSK/G16_mul.v:13.38-13.39" *)
  wire [1:0] p;
  (* src = "gadget_library/MSK/G16_mul.v:13.41-13.42" *)
  wire [1:0] q;
  (* src = "gadget_library/MSK/G16_mul.v:12.33-12.34" *)
  input [3:0] x;
  wire [3:0] x;
  (* src = "gadget_library/MSK/G16_mul.v:12.53-12.54" *)
  input [3:0] y;
  wire [3:0] y;
  (* src = "gadget_library/MSK/G16_mul.v:12.74-12.75" *)
  output [3:0] z;
  wire [3:0] z;
  XOR2_X1 _04_ (
    .A(x[2]),
    .B(x[0]),
    .Z(_00_)
  );
  XOR2_X1 _05_ (
    .A(x[3]),
    .B(x[1]),
    .Z(_01_)
  );
  XOR2_X1 _06_ (
    .A(y[2]),
    .B(y[0]),
    .Z(_02_)
  );
  XOR2_X1 _07_ (
    .A(y[3]),
    .B(y[1]),
    .Z(_03_)
  );
  XOR2_X1 _08_ (
    .A(p[0]),
    .B(e_scl[0]),
    .Z(z[2])
  );
  XOR2_X1 _09_ (
    .A(p[1]),
    .B(e_scl[1]),
    .Z(z[3])
  );
  XOR2_X1 _10_ (
    .A(e_scl[0]),
    .B(q[0]),
    .Z(z[0])
  );
  XOR2_X1 _11_ (
    .A(e_scl[1]),
    .B(q[1]),
    .Z(z[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "gadget_library/MSK/G16_mul.v:18.12-18.45" *)
  G4_mul mul1 (
    .x({ _01_, _00_ }),
    .y({ _03_, _02_ }),
    .z(e)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "gadget_library/MSK/G16_mul.v:20.12-20.37" *)
  G4_mul mul2 (
    .x(x[3:2]),
    .y(y[3:2]),
    .z(p)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "gadget_library/MSK/G16_mul.v:21.12-21.37" *)
  G4_mul mul3 (
    .x(x[1:0]),
    .y(y[1:0]),
    .z(q)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "gadget_library/MSK/G16_mul.v:19.14-19.37" *)
  G4_scl_N scl_N (
    .x(e),
    .z(e_scl)
  );
  assign a = x[3:2];
  assign b = x[1:0];
  assign c = y[3:2];
  assign d = y[1:0];
endmodule

(* src = "gadget_library/MSK/G4_mul.v:3.1-12.10" *)
module G4_mul(x, y, z);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "gadget_library/MSK/G4_mul.v:4.10-4.11" *)
  wire a;
  (* src = "gadget_library/MSK/G4_mul.v:4.13-4.14" *)
  wire b;
  (* src = "gadget_library/MSK/G4_mul.v:4.16-4.17" *)
  wire c;
  (* src = "gadget_library/MSK/G4_mul.v:4.19-4.20" *)
  wire d;
  (* src = "gadget_library/MSK/G4_mul.v:3.32-3.33" *)
  input [1:0] x;
  wire [1:0] x;
  (* src = "gadget_library/MSK/G4_mul.v:3.52-3.53" *)
  input [1:0] y;
  wire [1:0] y;
  (* src = "gadget_library/MSK/G4_mul.v:3.73-3.74" *)
  output [1:0] z;
  wire [1:0] z;
  NAND2_X1 _05_ (
    .A1(x[1]),
    .A2(y[1]),
    .ZN(_02_)
  );
  XNOR2_X1 _06_ (
    .A(x[1]),
    .B(x[0]),
    .ZN(_03_)
  );
  XNOR2_X1 _07_ (
    .A(y[1]),
    .B(y[0]),
    .ZN(_04_)
  );
  NOR2_X1 _08_ (
    .A1(_03_),
    .A2(_04_),
    .ZN(_00_)
  );
  XNOR2_X1 _09_ (
    .A(_02_),
    .B(_00_),
    .ZN(z[1])
  );
  NAND2_X1 _10_ (
    .A1(x[0]),
    .A2(y[0]),
    .ZN(_01_)
  );
  XNOR2_X1 _11_ (
    .A(_00_),
    .B(_01_),
    .ZN(z[0])
  );
  assign a = x[1];
  assign b = x[0];
  assign c = y[1];
  assign d = y[0];
endmodule

(* src = "gadget_library/MSK/G16_mul.v:3.1-9.10" *)
module G4_scl_N(x, z);
  (* src = "gadget_library/MSK/G16_mul.v:4.10-4.11" *)
  wire a;
  (* src = "gadget_library/MSK/G16_mul.v:4.13-4.14" *)
  wire b;
  (* src = "gadget_library/MSK/G16_mul.v:3.34-3.35" *)
  input [1:0] x;
  wire [1:0] x;
  (* src = "gadget_library/MSK/G16_mul.v:3.55-3.56" *)
  output [1:0] z;
  wire [1:0] z;
  XOR2_X1 _0_ (
    .A(x[1]),
    .B(x[0]),
    .Z(z[0])
  );
  assign a = x[1];
  assign b = x[0];
  assign z[1] = x[0];
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:10.1-736.10" *)
module canright(clk, i0, i1, i2, i3, i4, i5, i6, i7, o0, o1, o2, o3, o4, o5, o6, o7, rnd_0, rnd_1, rnd_2, rnd_3
);
  (* fv_type = "clock" *)
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:37.7-37.10" *)
  input clk;
  wire clk;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:78.14-78.20" *)
  wire [1:0] gen0_4;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:80.14-80.21" *)
  wire [1:0] gen10_0;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:81.14-81.21" *)
  wire [1:0] gen10_1;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:82.14-82.21" *)
  wire [1:0] gen10_2;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:83.14-83.21" *)
  wire [1:0] gen10_3;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:84.14-84.21" *)
  wire [1:0] gen11_0;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:85.14-85.21" *)
  wire [1:0] gen12_0;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:86.14-86.21" *)
  wire [1:0] gen12_1;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:87.14-87.21" *)
  wire [1:0] gen12_2;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:88.14-88.21" *)
  wire [1:0] gen12_3;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:89.14-89.21" *)
  wire [1:0] gen13_0;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:90.14-90.21" *)
  wire [1:0] gen14_0;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:91.14-91.21" *)
  wire [1:0] gen14_1;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:92.14-92.21" *)
  wire [1:0] gen14_2;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:93.14-93.21" *)
  wire [1:0] gen14_3;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:94.14-94.21" *)
  wire [1:0] gen15_0;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:95.14-95.21" *)
  wire [1:0] gen16_0;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:96.14-96.21" *)
  wire [1:0] gen16_1;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:97.14-97.21" *)
  wire [1:0] gen16_2;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:98.14-98.21" *)
  wire [1:0] gen16_3;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:99.14-99.21" *)
  wire [1:0] gen17_0;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:100.14-100.21" *)
  wire [1:0] gen18_0;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:101.14-101.21" *)
  wire [1:0] gen19_0;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:102.14-102.21" *)
  wire [1:0] gen19_1;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:103.14-103.21" *)
  wire [1:0] gen19_2;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:104.14-104.21" *)
  wire [1:0] gen19_3;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:79.14-79.20" *)
  wire [1:0] gen1_4;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:106.14-106.21" *)
  wire [1:0] gen20_0;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:107.14-107.21" *)
  wire [1:0] gen20_1;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:108.14-108.21" *)
  wire [1:0] gen20_2;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:109.14-109.21" *)
  wire [1:0] gen20_3;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:110.14-110.21" *)
  wire [1:0] gen21_0;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:111.14-111.21" *)
  wire [1:0] gen21_1;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:112.14-112.21" *)
  wire [1:0] gen21_2;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:113.14-113.21" *)
  wire [1:0] gen21_3;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:114.14-114.21" *)
  wire [1:0] gen22_1;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:115.14-115.21" *)
  wire [1:0] gen22_2;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:116.14-116.21" *)
  wire [1:0] gen23_1;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:117.14-117.21" *)
  wire [1:0] gen23_2;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:118.14-118.21" *)
  wire [1:0] gen24_2;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:119.14-119.21" *)
  wire [1:0] gen25_1;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:120.14-120.21" *)
  wire [1:0] gen25_2;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:121.14-121.21" *)
  wire [1:0] gen26_1;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:122.14-122.21" *)
  wire [1:0] gen26_2;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:123.14-123.21" *)
  wire [1:0] gen27_2;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:124.14-124.21" *)
  wire [1:0] gen28_2;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:125.14-125.21" *)
  wire [1:0] gen29_2;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:105.14-105.20" *)
  wire [1:0] gen2_4;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:127.14-127.21" *)
  wire [1:0] gen30_2;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:128.14-128.21" *)
  wire [1:0] gen30_3;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:129.14-129.21" *)
  wire [1:0] gen31_2;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:130.14-130.21" *)
  wire [1:0] gen32_2;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:131.14-131.21" *)
  wire [1:0] gen32_3;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:132.14-132.21" *)
  wire [1:0] gen33_1;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:133.14-133.21" *)
  wire [1:0] gen34_1;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:134.14-134.21" *)
  wire [1:0] gen35_1;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:135.14-135.21" *)
  wire [1:0] gen36_1;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:136.14-136.21" *)
  wire [1:0] gen37_1;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:137.14-137.21" *)
  wire [1:0] gen38_1;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:138.14-138.21" *)
  wire [1:0] gen39_1;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:126.14-126.20" *)
  wire [1:0] gen3_4;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:140.14-140.21" *)
  wire [1:0] gen40_1;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:141.14-141.21" *)
  wire [1:0] gen41_1;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:142.14-142.21" *)
  wire [1:0] gen42_1;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:143.14-143.21" *)
  wire [1:0] gen43_1;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:144.14-144.21" *)
  wire [1:0] gen44_4;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:145.14-145.21" *)
  wire [1:0] gen45_4;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:146.14-146.21" *)
  wire [1:0] gen46_4;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:147.14-147.21" *)
  wire [1:0] gen47_4;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:148.14-148.21" *)
  wire [1:0] gen48_4;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:149.14-149.21" *)
  wire [1:0] gen49_4;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:139.14-139.20" *)
  wire [1:0] gen4_0;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:151.14-151.21" *)
  wire [1:0] gen50_4;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:152.14-152.21" *)
  wire [1:0] gen51_4;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:153.14-153.21" *)
  wire [1:0] gen52_4;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:154.14-154.21" *)
  wire [1:0] gen53_4;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:155.14-155.21" *)
  wire [1:0] gen54_4;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:156.14-156.21" *)
  wire [1:0] gen55_4;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:157.14-157.21" *)
  wire [1:0] gen56_4;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:158.14-158.21" *)
  wire [1:0] gen57_4;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:159.14-159.21" *)
  wire [1:0] gen58_4;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:160.14-160.21" *)
  wire [1:0] gen59_3;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:161.14-161.21" *)
  wire [1:0] gen59_4;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:150.14-150.20" *)
  wire [1:0] gen5_0;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:163.14-163.21" *)
  wire [1:0] gen60_3;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:164.14-164.21" *)
  wire [1:0] gen60_4;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:165.14-165.21" *)
  wire [1:0] gen61_3;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:166.14-166.21" *)
  wire [1:0] gen61_4;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:167.14-167.21" *)
  wire [1:0] gen62_3;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:168.14-168.21" *)
  wire [1:0] gen62_4;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:162.14-162.20" *)
  wire [1:0] gen6_0;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:169.14-169.20" *)
  wire [1:0] gen7_0;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:170.14-170.20" *)
  wire [1:0] gen8_0;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:171.14-171.20" *)
  wire [1:0] gen9_0;
  (* fv_count = 32'd1 *)
  (* fv_latency = 32'd0 *)
  (* fv_type = "sharing" *)
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:39.15-39.17" *)
  input [1:0] i0;
  wire [1:0] i0;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:172.14-172.18" *)
  wire [1:0] i0_0;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:173.14-173.18" *)
  wire [1:0] i0_1;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:174.14-174.18" *)
  wire [1:0] i0_2;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:175.14-175.18" *)
  wire [1:0] i0_3;
  (* fv_count = 32'd1 *)
  (* fv_latency = 32'd0 *)
  (* fv_type = "sharing" *)
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:41.15-41.17" *)
  input [1:0] i1;
  wire [1:0] i1;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:176.14-176.18" *)
  wire [1:0] i1_0;
  (* fv_count = 32'd1 *)
  (* fv_latency = 32'd0 *)
  (* fv_type = "sharing" *)
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:43.15-43.17" *)
  input [1:0] i2;
  wire [1:0] i2;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:177.14-177.18" *)
  wire [1:0] i2_0;
  (* fv_count = 32'd1 *)
  (* fv_latency = 32'd0 *)
  (* fv_type = "sharing" *)
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:45.15-45.17" *)
  input [1:0] i3;
  wire [1:0] i3;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:178.14-178.18" *)
  wire [1:0] i3_0;
  (* fv_count = 32'd1 *)
  (* fv_latency = 32'd0 *)
  (* fv_type = "sharing" *)
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:47.15-47.17" *)
  input [1:0] i4;
  wire [1:0] i4;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:179.14-179.18" *)
  wire [1:0] i4_0;
  (* fv_count = 32'd1 *)
  (* fv_latency = 32'd0 *)
  (* fv_type = "sharing" *)
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:49.15-49.17" *)
  input [1:0] i5;
  wire [1:0] i5;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:180.14-180.18" *)
  wire [1:0] i5_0;
  (* fv_count = 32'd1 *)
  (* fv_latency = 32'd0 *)
  (* fv_type = "sharing" *)
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:51.15-51.17" *)
  input [1:0] i6;
  wire [1:0] i6;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:181.14-181.18" *)
  wire [1:0] i6_0;
  (* fv_count = 32'd1 *)
  (* fv_latency = 32'd0 *)
  (* fv_type = "sharing" *)
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:53.15-53.17" *)
  input [1:0] i7;
  wire [1:0] i7;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:182.14-182.18" *)
  wire [1:0] i7_0;
  (* fv_count = 32'd1 *)
  (* fv_latency = 32'd4 *)
  (* fv_type = "sharing" *)
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:55.16-55.18" *)
  output [1:0] o0;
  wire [1:0] o0;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:183.14-183.18" *)
  wire [1:0] o0_4;
  (* fv_count = 32'd1 *)
  (* fv_latency = 32'd4 *)
  (* fv_type = "sharing" *)
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:57.16-57.18" *)
  output [1:0] o1;
  wire [1:0] o1;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:184.14-184.18" *)
  wire [1:0] o1_4;
  (* fv_count = 32'd1 *)
  (* fv_latency = 32'd4 *)
  (* fv_type = "sharing" *)
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:59.16-59.18" *)
  output [1:0] o2;
  wire [1:0] o2;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:185.14-185.18" *)
  wire [1:0] o2_4;
  (* fv_count = 32'd1 *)
  (* fv_latency = 32'd4 *)
  (* fv_type = "sharing" *)
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:61.16-61.18" *)
  output [1:0] o3;
  wire [1:0] o3;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:186.14-186.18" *)
  wire [1:0] o3_4;
  (* fv_count = 32'd1 *)
  (* fv_latency = 32'd4 *)
  (* fv_type = "sharing" *)
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:63.16-63.18" *)
  output [1:0] o4;
  wire [1:0] o4;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:187.14-187.18" *)
  wire [1:0] o4_4;
  (* fv_count = 32'd1 *)
  (* fv_latency = 32'd4 *)
  (* fv_type = "sharing" *)
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:65.16-65.18" *)
  output [1:0] o5;
  wire [1:0] o5;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:188.14-188.18" *)
  wire [1:0] o5_4;
  (* fv_count = 32'd1 *)
  (* fv_latency = 32'd4 *)
  (* fv_type = "sharing" *)
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:67.16-67.18" *)
  output [1:0] o6;
  wire [1:0] o6;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:189.14-189.18" *)
  wire [1:0] o6_4;
  (* fv_count = 32'd1 *)
  (* fv_latency = 32'd4 *)
  (* fv_type = "sharing" *)
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:69.16-69.18" *)
  output [1:0] o7;
  wire [1:0] o7;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:190.14-190.18" *)
  wire [1:0] o7_4;
  (* fv_count = 32'd1 *)
  (* fv_rnd_count_0 = 32'd8 *)
  (* fv_rnd_lat_0 = 32'd0 *)
  (* fv_type = "random" *)
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:71.27-71.32" *)
  input [7:0] rnd_0;
  wire [7:0] rnd_0;
  (* fv_count = 32'd1 *)
  (* fv_rnd_count_0 = 32'd4 *)
  (* fv_rnd_lat_0 = 32'd1 *)
  (* fv_type = "random" *)
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:73.27-73.32" *)
  input [3:0] rnd_1;
  wire [3:0] rnd_1;
  (* fv_count = 32'd1 *)
  (* fv_rnd_count_0 = 32'd8 *)
  (* fv_rnd_lat_0 = 32'd2 *)
  (* fv_type = "random" *)
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:75.27-75.32" *)
  input [7:0] rnd_2;
  wire [7:0] rnd_2;
  (* fv_count = 32'd1 *)
  (* fv_rnd_count_0 = 32'd16 *)
  (* fv_rnd_lat_0 = 32'd3 *)
  (* fv_type = "random" *)
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:77.27-77.32" *)
  input [15:0] rnd_3;
  wire [15:0] rnd_3;
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:505.17-509.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen0_4 (
    .ina(gen49_4),
    .inb(gen53_4),
    .out(gen0_4)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:289.17-293.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen10_0 (
    .ina(gen5_0),
    .inb(i6),
    .out(gen10_0)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:219.17-223.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen11_0 (
    .ina(i0),
    .inb(i5),
    .out(gen11_0)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:244.17-248.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen12_0 (
    .ina(gen11_0),
    .inb(i6),
    .out(gen12_0)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:239.17-243.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen13_0 (
    .ina(gen6_0),
    .inb(i5),
    .out(gen13_0)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:269.17-273.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen14_0 (
    .ina(gen13_0),
    .inb(i6),
    .out(gen14_0)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:224.17-228.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen15_0 (
    .ina(gen9_0),
    .inb(i5),
    .out(gen15_0)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:249.17-253.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen16_0 (
    .ina(gen15_0),
    .inb(i6),
    .out(gen16_0)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:264.17-268.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen17_0 (
    .ina(gen4_0),
    .inb(i5),
    .out(gen17_0)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:294.17-298.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen18_0 (
    .ina(gen17_0),
    .inb(i6),
    .out(gen18_0)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:284.17-288.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen19_0 (
    .ina(gen8_0),
    .inb(i7),
    .out(gen19_0)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:510.17-514.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen1_4 (
    .ina(gen49_4),
    .inb(gen57_4),
    .out(gen1_4)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:274.17-278.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen20_0 (
    .ina(gen12_0),
    .inb(i7),
    .out(gen20_0)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:329.17-333.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen21_0 (
    .ina(gen18_0),
    .inb(i7),
    .out(gen21_0)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:374.17-378.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen22_1 (
    .ina(gen38_1),
    .inb(gen42_1),
    .out(gen22_1)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:339.17-343.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen23_1 (
    .ina(gen34_1),
    .inb(gen39_1),
    .out(gen23_1)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:379.17-383.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen24_2 (
    .ina(gen22_2),
    .inb(gen23_2),
    .out(gen24_2)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:354.17-358.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen25_1 (
    .ina(gen35_1),
    .inb(gen43_1),
    .out(gen25_1)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:359.17-363.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen26_1 (
    .ina(gen40_1),
    .inb(gen41_1),
    .out(gen26_1)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:369.17-373.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen27_2 (
    .ina(gen25_2),
    .inb(gen26_2),
    .out(gen27_2)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:396.17-400.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen28_2 (
    .ina(gen24_2),
    .inb(gen27_2),
    .out(gen28_2)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:384.24-395.2" *)
  \$paramod\MSKg4mul_hpc3\d=s32'00000000000000000000000000000010  comp_gen29_2 (
    .clk(clk),
    .ina0(gen22_1),
    .ina0_prev(gen22_2),
    .ina1(gen25_1),
    .ina1_prev(gen25_2),
    .inb0(gen23_1),
    .inb1(gen26_1),
    .out0(gen29_2),
    .out1(gen31_2),
    .rnd(rnd_1)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:490.17-494.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen2_4 (
    .ina(gen51_4),
    .inb(gen53_4),
    .out(gen2_4)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:406.17-410.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen30_2 (
    .ina(gen28_2),
    .inb(gen29_2),
    .out(gen30_2)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:401.17-405.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen32_2 (
    .ina(gen27_2),
    .inb(gen31_2),
    .out(gen32_2)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:279.17-283.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen33_1 (
    .ina(gen16_1),
    .inb(i0_1),
    .out(gen33_1)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:324.17-328.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen34_1 (
    .ina(gen20_1),
    .inb(gen10_1),
    .out(gen34_1)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:334.17-338.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen35_1 (
    .ina(gen33_1),
    .inb(gen34_1),
    .out(gen35_1)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:349.17-353.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen36_1 (
    .ina(gen21_1),
    .inb(gen19_1),
    .out(gen36_1)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:299.17-303.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen37_1 (
    .ina(gen14_1),
    .inb(gen12_1),
    .out(gen37_1)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:364.17-368.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen38_1 (
    .ina(gen36_1),
    .inb(gen37_1),
    .out(gen38_1)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:304.25-323.2" *)
  \$paramod\MSKg16mul_hpc3\d=s32'00000000000000000000000000000010  comp_gen39_1 (
    .clk(clk),
    .ina0(gen20_0),
    .ina0_prev(gen20_1),
    .ina1(gen14_0),
    .ina1_prev(gen14_1),
    .ina2(gen16_0),
    .ina2_prev(gen16_1),
    .ina3(gen21_0),
    .ina3_prev(gen21_1),
    .inb0(gen10_0),
    .inb1(gen12_0),
    .inb2(i0),
    .inb3(gen19_0),
    .out0(gen39_1),
    .out1(gen41_1),
    .out2(gen42_1),
    .out3(gen43_1),
    .rnd(rnd_0)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:500.17-504.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen3_4 (
    .ina(gen45_4),
    .inb(gen58_4),
    .out(gen3_4)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:344.17-348.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen40_1 (
    .ina(gen34_1),
    .inb(gen37_1),
    .out(gen40_1)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:485.17-489.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen44_4 (
    .ina(gen51_4),
    .inb(gen52_4),
    .out(gen44_4)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:520.17-524.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen46_4 (
    .ina(gen44_4),
    .inb(gen45_4),
    .out(gen46_4)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:435.25-454.2" *)
  \$paramod\MSKg16mul_hpc3\d=s32'00000000000000000000000000000010  comp_gen48_4 (
    .clk(clk),
    .ina0(gen61_3),
    .ina0_prev(gen61_4),
    .ina1(gen62_3),
    .ina1_prev(gen62_4),
    .ina2(gen59_3),
    .ina2_prev(gen59_4),
    .ina3(gen60_3),
    .ina3_prev(gen60_4),
    .inb0(gen10_3),
    .inb1(gen12_3),
    .inb2(i0_3),
    .inb3(gen19_3),
    .out0(gen48_4),
    .out1(gen57_4),
    .out2(gen53_4),
    .out3(gen58_4),
    .rnd(rnd_3[7:0])
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:475.17-479.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen49_4 (
    .ina(gen47_4),
    .inb(gen48_4),
    .out(gen49_4)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:234.17-238.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen4_0 (
    .ina(gen6_0),
    .inb(i2),
    .out(gen4_0)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:480.17-484.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen50_4 (
    .ina(gen45_4),
    .inb(gen48_4),
    .out(gen50_4)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:455.25-474.2" *)
  \$paramod\MSKg16mul_hpc3\d=s32'00000000000000000000000000000010  comp_gen51_4 (
    .clk(clk),
    .ina0(gen61_3),
    .ina0_prev(gen61_4),
    .ina1(gen62_3),
    .ina1_prev(gen62_4),
    .ina2(gen59_3),
    .ina2_prev(gen59_4),
    .ina3(gen60_3),
    .ina3_prev(gen60_4),
    .inb0(gen20_3),
    .inb1(gen14_3),
    .inb2(gen16_3),
    .inb3(gen21_3),
    .out0(gen51_4),
    .out1(gen47_4),
    .out2(gen52_4),
    .out3(gen45_4),
    .rnd(rnd_3[15:8])
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:551.17-555.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen54_4 (
    .ina(gen46_4),
    .inb(gen57_4),
    .out(gen54_4)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:515.17-519.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen55_4 (
    .ina(gen50_4),
    .inb(gen57_4),
    .out(gen55_4)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:546.17-550.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen56_4 (
    .ina(gen55_4),
    .inb(gen53_4),
    .out(gen56_4)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:411.24-422.2" *)
  \$paramod\MSKg4mul_hpc3\d=s32'00000000000000000000000000000010  comp_gen59_3 (
    .clk(clk),
    .ina0(gen32_2),
    .ina0_prev(gen32_3),
    .ina1(gen30_2),
    .ina1_prev(gen30_3),
    .inb0(gen23_2),
    .inb1(gen26_2),
    .out0(gen59_3),
    .out1(gen60_3),
    .rnd(rnd_2[3:0])
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:259.17-263.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen5_0 (
    .ina(gen4_0),
    .inb(i3),
    .out(gen5_0)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:423.24-434.2" *)
  \$paramod\MSKg4mul_hpc3\d=s32'00000000000000000000000000000010  comp_gen61_3 (
    .clk(clk),
    .ina0(gen32_2),
    .ina0_prev(gen32_3),
    .ina1(gen30_2),
    .ina1_prev(gen30_3),
    .inb0(gen22_2),
    .inb1(gen25_2),
    .out0(gen61_3),
    .out1(gen62_3),
    .rnd(rnd_2[7:4])
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:214.17-218.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen6_0 (
    .ina(i0),
    .inb(i1),
    .out(gen6_0)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:229.17-233.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen7_0 (
    .ina(gen6_0),
    .inb(i3),
    .out(gen7_0)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:254.17-258.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen8_0 (
    .ina(gen7_0),
    .inb(i4),
    .out(gen8_0)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:209.17-213.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_gen9_0 (
    .ina(i0),
    .inb(i4),
    .out(gen9_0)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:538.17-541.2" *)
  \$paramod\MSKinv\d=s32'00000000000000000000000000000010  comp_o0_4 (
    .in(gen0_4),
    .out(o0_4)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:542.17-545.2" *)
  \$paramod\MSKinv\d=s32'00000000000000000000000000000010  comp_o1_4 (
    .in(gen1_4),
    .out(o1_4)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:561.17-565.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_o2_4 (
    .ina(gen54_4),
    .inb(gen53_4),
    .out(o2_4)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:556.17-560.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_o3_4 (
    .ina(gen56_4),
    .inb(gen58_4),
    .out(o3_4)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:529.17-533.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_o4_4 (
    .ina(o7_4),
    .inb(gen58_4),
    .out(o4_4)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:525.17-528.2" *)
  \$paramod\MSKinv\d=s32'00000000000000000000000000000010  comp_o5_4 (
    .in(gen2_4),
    .out(o5_4)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:534.17-537.2" *)
  \$paramod\MSKinv\d=s32'00000000000000000000000000000010  comp_o6_4 (
    .in(gen3_4),
    .out(o6_4)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:495.17-499.2" *)
  \$paramod\MSKxor\d=s32'00000000000000000000000000000010  comp_o7_4 (
    .ina(gen45_4),
    .inb(gen57_4),
    .out(o7_4)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:671.17-675.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen10_0 (
    .clk(clk),
    .in(gen10_0),
    .out(gen10_1)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:676.17-680.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen10_1 (
    .clk(clk),
    .in(gen10_1),
    .out(gen10_2)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:681.17-685.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen10_2 (
    .clk(clk),
    .in(gen10_2),
    .out(gen10_3)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:606.17-610.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen12_0 (
    .clk(clk),
    .in(gen12_0),
    .out(gen12_1)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:611.17-615.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen12_1 (
    .clk(clk),
    .in(gen12_1),
    .out(gen12_2)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:616.17-620.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen12_2 (
    .clk(clk),
    .in(gen12_2),
    .out(gen12_3)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:656.17-660.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen14_0 (
    .clk(clk),
    .in(gen14_0),
    .out(gen14_1)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:661.17-665.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen14_1 (
    .clk(clk),
    .in(gen14_1),
    .out(gen14_2)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:666.17-670.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen14_2 (
    .clk(clk),
    .in(gen14_2),
    .out(gen14_3)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:576.17-580.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen16_0 (
    .clk(clk),
    .in(gen16_0),
    .out(gen16_1)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:581.17-585.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen16_1 (
    .clk(clk),
    .in(gen16_1),
    .out(gen16_2)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:586.17-590.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen16_2 (
    .clk(clk),
    .in(gen16_2),
    .out(gen16_3)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:621.17-625.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen19_0 (
    .clk(clk),
    .in(gen19_0),
    .out(gen19_1)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:626.17-630.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen19_1 (
    .clk(clk),
    .in(gen19_1),
    .out(gen19_2)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:631.17-635.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen19_2 (
    .clk(clk),
    .in(gen19_2),
    .out(gen19_3)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:641.17-645.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen20_0 (
    .clk(clk),
    .in(gen20_0),
    .out(gen20_1)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:646.17-650.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen20_1 (
    .clk(clk),
    .in(gen20_1),
    .out(gen20_2)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:651.17-655.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen20_2 (
    .clk(clk),
    .in(gen20_2),
    .out(gen20_3)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:706.17-710.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen21_0 (
    .clk(clk),
    .in(gen21_0),
    .out(gen21_1)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:711.17-715.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen21_1 (
    .clk(clk),
    .in(gen21_1),
    .out(gen21_2)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:716.17-720.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen21_2 (
    .clk(clk),
    .in(gen21_2),
    .out(gen21_3)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:636.17-640.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen22_1 (
    .clk(clk),
    .in(gen22_1),
    .out(gen22_2)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:691.17-695.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen23_1 (
    .clk(clk),
    .in(gen23_1),
    .out(gen23_2)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:731.17-735.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen25_1 (
    .clk(clk),
    .in(gen25_1),
    .out(gen25_2)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:686.17-690.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen26_1 (
    .clk(clk),
    .in(gen26_1),
    .out(gen26_2)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:726.17-730.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen30_2 (
    .clk(clk),
    .in(gen30_2),
    .out(gen30_3)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:721.17-725.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen32_2 (
    .clk(clk),
    .in(gen32_2),
    .out(gen32_3)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:701.17-705.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen59_3 (
    .clk(clk),
    .in(gen59_3),
    .out(gen59_4)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:696.17-700.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen60_3 (
    .clk(clk),
    .in(gen60_3),
    .out(gen60_4)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:566.17-570.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen61_3 (
    .clk(clk),
    .in(gen61_3),
    .out(gen61_4)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:571.17-575.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_gen62_3 (
    .clk(clk),
    .in(gen62_3),
    .out(gen62_4)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:591.17-595.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_i0_0 (
    .clk(clk),
    .in(i0),
    .out(i0_1)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:596.17-600.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_i0_1 (
    .clk(clk),
    .in(i0_1),
    .out(i0_2)
  );
  (* src = "../work/canright_aes_sbox_opt/circuits/canright_d2_l4/design.v:601.17-605.2" *)
  \$paramod\MSKreg\d=s32'00000000000000000000000000000010  reg_i0_2 (
    .clk(clk),
    .in(i0_2),
    .out(i0_3)
  );
  assign i0_0 = i0;
  assign i1_0 = i1;
  assign i2_0 = i2;
  assign i3_0 = i3;
  assign i4_0 = i4;
  assign i5_0 = i5;
  assign i6_0 = i6;
  assign i7_0 = i7;
  assign o0 = o0_4;
  assign o1 = o1_4;
  assign o2 = o2_4;
  assign o3 = o3_4;
  assign o4 = o4_4;
  assign o5 = o5_4;
  assign o6 = o6_4;
  assign o7 = o7_4;
endmodule
