name: Build documentation
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v**
  pull_request:
    branches:
      - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: docs
          root_file: SMAesH.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/SMAesH.pdf

  release:
    needs: [build_latex]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: docs
          path: release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            View CHANGELOG.md for full changes.
          files: |
            release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  functest:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true
      - run: sudo apt-get install -y yosys verilator iverilog
      - run: make func-tests 

  formal_verif_matchi:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true
      - run: sudo apt-get install -y yosys iverilog
      - run: mkdir verif-tools
      - run: wget https://github.com/cassiersg/matchi/releases/download/v0.1.0/matchi -P ./verif-tools
      - run: chmod +x ${{ github.workspace }}/verif-tools/matchi
      - run: (cd verif-tools; curl -L https://github.com/cassiersg/matchi/archive/refs/tags/v0.1.0.tar.gz | tar zxf)
      - run: (curl -L https://github.com/simple-crypto/hw-devtools/releases/download/v241002/hw-devtools.tar.gz | tar xz; sudo apt install ./hw-devtools/*.deb)
      - run: make formal-tests MATCHI_CELLS=${{ github.workspace }}/verif-tools/matchi-0.1.0/matchi_cells MATCHI_BIN=${{ github.workspace }}/verif-tools/matchi


            
