name: Build documentation
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v**
  pull_request:
    branches:
      - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: docs
          root_file: SMAesH.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/SMAesH.pdf

  release:
    needs: [build_latex]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: docs
          path: release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            View CHANGELOG.md for full changes.
          files: |
            release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  functest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install Iverilog
        uses: supplypike/setup-bin@v4
        with:
          uri: 'https://github.com/stnolting/icarus-verilog-prebuilt/releases/download/v1.0.0/iverilog-27082022.tar.gz'
      - run: iverilog
            
